### ISSUE TITLE
Add different kernels for SVM

### ISSUE THREAD

**Issue by AnupKumarGupta** [AnupKumarGupta/Machine-Learning-Lab-Assignments#1]
1. Use different Kernel SVMs for classification
2. Display the confusion matrix and print the **Precision** and **Recall** values of the model.

> Confusion Matrix

![image](https://user-images.githubusercontent.com/13765996/66206052-87f1d300-e6cc-11e9-8550-29d1aebf364e.png)
Image Courtesy: [Confusion Matrix and Advanced Classification Metrics](https://manisha-sirsat.blogspot.com/2019/04/confusion-matrix.html)

**Comment by 12345k** [comment]
can you share the dataset

**Comment by AnupKumarGupta** [comment]
> can you share the dataset

Added

**Comment by AnupKumarGupta** [comment]
@12345k I will be adding a new issue for adding newer models, if you are interested you can pickup that. Closing this issue with a commit.
